version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.data/db:/var/lib/postgresql/data:delegated
    ports:
      - 9876:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9877:8080
