version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.data/db:/var/lib/postgresql/data:delegated
    restart: unless-stopped

  covid-nl-bot:
    image: nheisterkamp/covid-nl-bot:latest
    build: .
    environment:
      API_TOKEN: ${API_TOKEN}
      POSTGRES_URL: ${POSTGRES_URL}
    depends_on:
      - db
    volumes:
      - ./data:/app/data
